fasitUrl: https://fasit.example.com
clusterName: kubernetes
repository: navikt/named
minReplicas: 2
maxReplicas: 4
targetCPUUtilizationPercentage: 50
runAsUser: 10001
request:
  memory: 64Mi
  cpu: 250m
limit:
  memory: 128Mi
  cpu: 500m
version: 94.0.0
