sudo: required
services:
- docker
before_script:
- docker pull navikt/glide
- docker pull golang:1.8
- docker pull navikt/helm
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- git clone https://github.com/nais/charts
script:
- make install test linux cli-dist
- "/bin/bash bump.sh $GH_TOKEN"
- git tag -a $(/bin/cat ./version) -m "auto-tag from Makefile [skip ci]" && git push
  --tags https://$GH_TOKEN@github.com/nais/named
- make docker-build push-dockerhub
- cd charts
- docker run -v $(pwd):/charts -v $(pwd)/../:/named -w /charts navikt/helm package
  /named/helm/named
- docker run -v $(pwd):/charts -w /charts navikt/helm repo index --url https://nais.github.io/charts
  .
- echo "<html><body><pre>$(cat index.yaml)</pre></body></html>" > index.html
- git add --all
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/charts
- cd ..
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: nais-*
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
env:
  global:
  - secure: PcjqCRXcr5XbEfLMH6H+96J8717vymzDRdvDk63Uu/bR4biPRKwDgXQs4KARrIuSu31JlE3IjLd7PsIU8s042FfUe1GGUjNZ9qWmftatRHFBtxBIf5LRo6rThwNlzz9GRkr9LdDlfs09rI1cY5DSUHgKzikDpJnq9nHEJ3oQ3UonXXZfbYksMdQS6j4mfNWBTlvT/avM5MTNdrBTDuA6X/CRrTIEP/cj0mFAeocNLDOyhz/04OvxTkFFdmbywOs+Vcwf3X4WbKFq3HRA0IZ924uUKU2kqHyW8/qp+SAssZKKmjZjdfQ8mvWL5Y29p1YzL5Ip94oKMlWOIrRSXeVvFyI0bQJ77H0O4ppVO0e010EbdR2KmqkNcsL7Bqg7jgJjQe6qKLl7Sc3h+oP7i9iLOcQYtABNuygzZdKjTgLkTfRRX7irSK3yOrQWas82iGyzV97ewNu8cfMgGqgdgtSJrfzbsGkJ9ZqByuvvPC9oqasc1zL5xmNolfYgwRSx2a+W613CSvjtwT9moOeKMlxK2kC9pPXtmoNn6D+Viyyso2zQuI7Kxq8KsAPjbTrkZA8eI15aNa4KTv/7PMqDg84ifBYgNu2oTg1WVYC83vX+LlOPapx9uZZzoJM+SZStjSPBgQUrVVoP2bkPJawnEVizV9e46pcWH6E2xsNMU4QRoiY=
notifications:
  slack:
    secure: xYTqHowKT9fkEz3hnd8q3uJGIW+clEUwOxc46tg/s0k5/0KzRS1BdvbLM6AWN4zpTII9AHiYU8mE39vICNXUrrLs7xhRm/gXOiACplGvdbvMliUY9jBDRW2N8muexz1sqTqy5qFp/vmJKHqeQKGSkamyE4Bv8Tg/0MnJMx6piNj8NqLWWiuosJbvt4kY6ZInB33NTrt7AQuaqnHPrL0eADQNxORNHDbnOsmVl7ApswEnUndEZ+h6abXgZAIelFhJTuOYnH2Py+XpcdxPNK7udy/qL78Aji1WrDxKMnY+Lhq1jhQGez0hMlpZyoaLVNkh5ZhWIgJB3zI3rg9ndNKEqGL0MreRsm2h1yFQMPMzItJ3xcsi8OWi62P8cA1AKFpzEZAZuZN+bOKStWdDUwOOeQXbYb137Fs7l8da2Wx+JuQc0FsxFqYSV5fV0aXjviNa16eB8xsUOKCx7fU3O9CTkxdqn+Evn1RMSCvSVlJwv3v+SESg+17TCFxk+m7AqJxPiewqzqODqY2WHOiQAGHT2x7vVp2QH0gqOBWYjXT+UyFFS6Mq7fzXx49wbBrOBzCnnURSWJ1k1/HGNyU19pFI95PDinhLrwVQ9ZzZ5ewm5W41vI/tHKZyIim9v4lpYByznMu0AlJ6PuWaNL5I1tnvbn9OPPDU8eWMpoDmelr7Tgk=
