sudo: required
services:
- docker
before_script:
- docker pull navikt/glide
- docker pull golang:1.8
- docker pull navikt/helm
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- git clone https://github.com/nais/charts
script:
- make install test linux cli-dist
- "/bin/bash bump.sh $GH_TOKEN"
- git tag -a $(/bin/cat ./version) -m "auto-tag from Makefile [skip ci]" && git push
  --tags https://$GH_TOKEN@github.com/nais/named
- make docker-build push-dockerhub
- cd charts
- docker run -v $(pwd):/charts -v $(pwd)/../:/named -w /charts navikt/helm package
  /named/helm/named
- docker run -v $(pwd):/charts -w /charts navikt/helm repo index --url https://nais.github.io/charts
  .
- echo "<html><body><pre>$(cat index.yaml)</pre></body></html>" > index.html
- git add --all
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/charts
- cd ..
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: nais-*
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: xYTqHowKT9fkEz3hnd8q3uJGIW+clEUwOxc46tg/s0k5/0KzRS1BdvbLM6AWN4zpTII9AHiYU8mE39vICNXUrrLs7xhRm/gXOiACplGvdbvMliUY9jBDRW2N8muexz1sqTqy5qFp/vmJKHqeQKGSkamyE4Bv8Tg/0MnJMx6piNj8NqLWWiuosJbvt4kY6ZInB33NTrt7AQuaqnHPrL0eADQNxORNHDbnOsmVl7ApswEnUndEZ+h6abXgZAIelFhJTuOYnH2Py+XpcdxPNK7udy/qL78Aji1WrDxKMnY+Lhq1jhQGez0hMlpZyoaLVNkh5ZhWIgJB3zI3rg9ndNKEqGL0MreRsm2h1yFQMPMzItJ3xcsi8OWi62P8cA1AKFpzEZAZuZN+bOKStWdDUwOOeQXbYb137Fs7l8da2Wx+JuQc0FsxFqYSV5fV0aXjviNa16eB8xsUOKCx7fU3O9CTkxdqn+Evn1RMSCvSVlJwv3v+SESg+17TCFxk+m7AqJxPiewqzqODqY2WHOiQAGHT2x7vVp2QH0gqOBWYjXT+UyFFS6Mq7fzXx49wbBrOBzCnnURSWJ1k1/HGNyU19pFI95PDinhLrwVQ9ZzZ5ewm5W41vI/tHKZyIim9v4lpYByznMu0AlJ6PuWaNL5I1tnvbn9OPPDU8eWMpoDmelr7Tgk=
env:
  global:
  - secure: PcjqCRXcr5XbEfLMH6H+96J8717vymzDRdvDk63Uu/bR4biPRKwDgXQs4KARrIuSu31JlE3IjLd7PsIU8s042FfUe1GGUjNZ9qWmftatRHFBtxBIf5LRo6rThwNlzz9GRkr9LdDlfs09rI1cY5DSUHgKzikDpJnq9nHEJ3oQ3UonXXZfbYksMdQS6j4mfNWBTlvT/avM5MTNdrBTDuA6X/CRrTIEP/cj0mFAeocNLDOyhz/04OvxTkFFdmbywOs+Vcwf3X4WbKFq3HRA0IZ924uUKU2kqHyW8/qp+SAssZKKmjZjdfQ8mvWL5Y29p1YzL5Ip94oKMlWOIrRSXeVvFyI0bQJ77H0O4ppVO0e010EbdR2KmqkNcsL7Bqg7jgJjQe6qKLl7Sc3h+oP7i9iLOcQYtABNuygzZdKjTgLkTfRRX7irSK3yOrQWas82iGyzV97ewNu8cfMgGqgdgtSJrfzbsGkJ9ZqByuvvPC9oqasc1zL5xmNolfYgwRSx2a+W613CSvjtwT9moOeKMlxK2kC9pPXtmoNn6D+Viyyso2zQuI7Kxq8KsAPjbTrkZA8eI15aNa4KTv/7PMqDg84ifBYgNu2oTg1WVYC83vX+LlOPapx9uZZzoJM+SZStjSPBgQUrVVoP2bkPJawnEVizV9e46pcWH6E2xsNMU4QRoiY=
  - secure: HugIQaKXL26nMYLxcHJjBon9XIZOKhZA1WEEzWvwGgl0b6KnwFhBrK+/ytj+HmL7A5y2OVv2OyjmJMaBpqWFIfIvIOXRjWE7ZhHmStMi7/mhoVzsVnxMb5pZqQVOAxIByQeO09+Xsj6fc/fy6NWKoYCQj77FIyYxU4slcdsVFiwRZg4LqYz6e1iOv8kdhEXyd443IG0/UFMXuGQGyiZCYbGjNkQDwrnlGFR+BrQkj+xOLFwLOFPGHZJ2UXNVXaI/DBPSxk+/rYRC1466PpgTZ3MMGfN9dCA0t7z3wIEqRyHXl++r4YDOGrjlbl53AMZbCMdaI4/futyYlVoo4ys6FoeXUH7keRgzKxjrlEZfG3b59hAipdv9LHVkRkJ1HCvHSHXksAWWgCXcFsvRptsY5j5hQSJ9sOld/r0up5+xQRxqHayb0RsGaHOl8fZ0zMkVysGXW65QeRqcrcPUyo+NVLxDtlFsUlPJul59xQBxg0rPad26I4Ksjbr9qhCRUjckjD/PhKRDtJk66Wprkfxvt1gmZTyyiH5QkfU3hciQWJzLeSh62EX5hMwDb/aj0e3BBGLJdAxxUamUNys3cvi27EsuJ7HvsKgdWoFcEQS0inSULlR72nkhFjlZ5xCDuKuSNeG7o6ZLUjRQ7h/N1XMBT7CdGL9hx6F2SqS+wHGwgmU=
  - secure: isVy0wDidruZmAUJ/EhNmKpp+Pe/b6rTR9H4zQjXunvwGPReIvT3OBEFFki2KIAYdxExUS14eC7A4VsUQr4LhTYwzLA2HGE2dAH9xoZZNavOOLggRmPbypJSJEIsnzZijwbDHmizd+eAY0C/SGVBBpFoj5QHol4/eEn+xRYb1WPac8C0C8WCko9Cvxl99CMkFRESIo+hiJC7wGyEExLia8l+yfCxa71H9sOVe4tjUq46yIX6XwQga+8cZ+/9pHvOlMgq3apa64boww3sSGB5K4nKmd1yv02j75smqpD/vqfqldbnPrKQftdGULZHHI7eOSy55pR2cyjKVgG3EOSGZsuTBhKP5/TIaduBXlLdcfv5swASTIJXUI3lddK/csv8lKb/jEg3NPrNclcKcFBQVDvO1WxCbJUnoy1Ly115OAOdJWx+CGZRfeOE+S8ROH2PXh+AodRYaWJHA/Oj10tu8uNL4RJmWxLulEN6oMBDDXrj1JzhN8a+gHs+Rj84XuHIGxKT0cU53nGG9/TeUSykLqIiqSybNKfsYhbkaMdia3rGqrrKSxqfH1jiUDEveYT1O6OwdHKjqRI/J9f1xEn5uU0SZEdcg3YU06BwKINXZK3GjetxunR5C1QR+QDjfk+gYvxRKrCta9oyoJh7RNSCWeBTQYnhSr7TB42O8s/Q91U=
  - secure: 32+CbegPgkBav9q4d4quK10prFQrjTe6v3k1/Z5f0P4Zr4JLLMlqYzo0oAvrFV/GRVH0PmuO6p58WWq7wKh/Ndc8F8eS82X8ymyzQTneFziDyoK4PgYmYhGbanUcyYSsRDPk4Pl58hhVwkOXE9vIBcrWOmyQQj8C6Z2gfTu1OmFYfPwKF7mDanFsiXwKqdli6osLrypAIQ588Xy1q5Yyp0UMCDk7kIZLUQoKFNxGXkGYO6BMyJFnOp1BwPHzcqGP6Rins/1kyZ4f0TtiBvtwH8VdKZ6BlK5brtqoveN1S7t1kevNsrJCqZ0V3Qw1Wi/Ia65ShJLyZrC0m2todjn+gobiptcXZI7HQXMyWUBzmCFHTpGRZ5JQbgpMj/r7jEtvUpRwK/fwqku8ba5x9yjpS/+LY6BPZilgUp2xoPKorsr5Vwywx11CdrbhtKl8m4dLoV90OnSYCjzVppJvCHACtyHdR56Eg3W4kXSYohzcXfEfuYMZf+E710EsPZbUtilmPWaa/OkmqF+yZKSh745Oca6au4CQCCXCa+30CURYBuwjbo2Srb6OcQwoQIRo2t66oyF4+KpH5oT2dpLb9U/stCwTbs1eIXA41zJim8ORS38200qe5X2UpIDebx6fZV0zmSmozz6HnmwjAq9GOsNGR/O8dX8Ggy0FeqQwyAloF04=
