sudo: required
services:
- docker
before_script:
- docker pull navikt/glide
- docker pull golang:1.8
- docker pull navikt/helm
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- git clone https://github.com/nais/charts
script:
- make install test linux cli-dist
- /bin/bash bump.sh $GH_TOKEN
- git tag -a $(/bin/cat ./version) -m "auto-tag from Makefile [skip ci]" && git push --tags https://$GH_TOKEN@github.com/nais/named
- make docker-build push-dockerhub
- cd charts
- docker run -v $(pwd):/charts -v $(pwd)/../:/naisd -w /charts navikt/helm package /named/helm/named
- docker run -v $(pwd):/charts -w /charts navikt/helm repo index --url https://nais.github.io/charts .
- echo "<html><body><pre>$(cat index.yaml)</pre></body></html>" > index.html
- git add --all
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/charts
- cd ..
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "nais-*"
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
  - master
env:
  global:
  - secure: tAqa9qeLHZPQkUHVbF3limHxDY2YcnyqMcc+10NmJhytdSwcLK0U2FWJ7B2JBg1G/MjPz5ZzLujyNmAwd5bc6iyk4g1+mxLpTz37Sn5oVRys1R4Jey5xiltuSGjYX8HFX3QlwSYvNAjHbr/U6xYix0xjvDxRh1TA43Oejfuoya8pCaR2AteW96JQ6iipdOBG2R1UqC1tnrkfdYYmN75lT6v8ApZMt6pJ66iuIuT5nclx2DXSkt0tm325OOFI9wU0HFxV5Vs/adKYLGs+OON7O60IyJmhf4G3NwLsJuRZ1fv02/2pxyzRKToZN7lv/9wHcH4TVpQ4uMCs4GgJKANGfOAaLUbsqMVfKhyFPVFHrPN423XeY6GqshfgJqUTEvlItH3H6omJ8opxe+Jz0Fe72BqXbN+9BBlgTM4DVoGppA1AmlpI9VeI0fvY1RIUfq2xw8qhhm+0q2ib8AqwtpUDELzCc8d4shZspvXpYpf7x7u1UYdu4+Wa1Mk2LJ0T+9zHWwABwMzt/A2XGqj5v04+UkauSV3zzS6H3x5eMLOAgQzQ3IUENv7ChbrsWToSUmEdFjKRfXmLzbaX8pX99mX6j8TnoLLE886XjuadVRJYiv3txRpg0qIzRJUAHbkmfH6sFVKdPSGtI/76rGbj44oupw66WuwIDh4Bxaij0DNk+i0=
  - secure: aLP9nF9FUyFs33NJhJMrYAW7U5nLsTklI1iLarh11Wf3O1BjcLWrbvpeoJoikTK9keOmDA5OzScJ3E/9lBoItfmbCUHd0Zz6EmF0rkTGcAZBpO7SYvsWP2c1AcfT7sW6SKwHLlMFO/llIScH5XrB0dC+eigM+hOmWykAtrpVRcb70L65iyf5AZYoAtEBZ1xjSBOMTzUQU/ePY7m3T/mRb5Zopr6xQQzYvDocuY0EgSU1n+GQxm4QPilzPlzhDF+ruI3i+Y/qiV+mAPodG/J9r1OcklEgXf+jxPbgY+HsZnRqBxSbSc1VHa8nyRBlKMekahRh5t3e3nPFHtAusJ+UfpZPx5ihYOBwpB+mIx2XAGniNypokXWcCgdTFXvXzU2Pgu6ozcf8YE030VCKVjlQxShqgUCPdOuET+UsWSdYbIBz+6nvNHztPgzjvVvf8kWwwyndaXfMHi/2CE39SszzuenaLd/IRbRDOu1vRIHxx/CpZ3ly8/CiLex7yuHTUFvBbXKc9O29wJWoCFFSGJzysCPqiOU6W39W5VrU2gDleVVgLK4XWNUSRkRSSooZ12dsLKbddkmSXqKEn7HfAPyPf/jyo7AFZgW7oO5N4E91qTsmb40xsg2bpgSdLRDb2gwvag+358+8TI6V+l4Pi7iQoOyd8cFDX5c+OUebvUZtbvE=
  - secure: JH+UXYbYECB3v+s5GTnpxypsWrKjngwFZdaZQVa93jYHKR1gWToEVz5pISQXdWw+5ZlRlejo4wiTgChBpnhYhTFYR3DidrPU9Bf9bPhukb5d6sXC8P5T3Dn0YyiGxUw2o2qnWt5Vj3EgZkj6fNrPI1S08aqKjMQ+2H1AaIyDexRWP7gu8iSBzqdZu7Y6pBIdUsERSBC2XVEMZBWlmQXfwVuI1fvKkWyq45JyUxfCiPi4jU3Cx2c3FZkR50QI6za+skGyujvf5VXiTJEcifdHEk4U8ICIkGx0nNFNV5ABtb49kvNq/X3w5/I2hF90NuiocXeHa+8E8gxaPkKNXV4Dvzopze0lzm6oYTEVKsP0Yjztigad4BYbNaL1DS7PuIq0t4szbftPDdsa5scuu+aEKvpZ7cnHwWNjwLz+rCHTHVbbgdw535+OxqZa6orw/wdwI0Rh20Y5z+c0djyoB30EhksfwGf7Z4KhPdVvhD2u/cfPEzhCgL2tUq1Lyo2GKybLzBygbgcMn0lEodKfcMTw2sBTVLalpqEpzrKDFAP9qXLpWZRW9CTmm/i+Ep4yJk7tufsWSf9E3ItpBNKXz673SopQHg4m2mj0mOcsN+rDnfuPXUnpkXvTRqLpRdjrhaPF46imXypzImQPbtDE3CJPFhJkkfFp7Z1jojeCdz8eI14=
  - secure: muQ2udRQSTVZVi7so3TqazLPrXgw4YptuAPpS349DMf2j5cDt4HvUfntvgMnEi9eZfC6SMMbVkEUVCIChUT4yQqJZo3TQWrQTQaMLKrzUk7oyDK/HusjuceqI/CJDyI+8VwQqFAqdepcp2CQXS+066GT6M4bPyvkbiRvB22vtTXASbBxV2wyrG73OT+KqwxcPUTj3UKDthQZ1dydeEwcU19hAWr/aL4Lchl9Q99SW1mWVVDvStMQ5TMMgXxuHTlRJybvm9ri0AiQs75suC1sXaZ4m93Uh/nzw3dT6aKZrIaR3WfN4BrvgEN08TNzuFavgAr4Ylqk+SISGGujMatDYoVA4RHA8nm7GFgQsmxj676rvN7e2dM4FgFOXnuLCd6DVgf6PoW9FSx3pu3TrwiR7c9bujHaTMk/E4PFu2ChATwsPfXoPcyZi/6+mho0+94YH6Z55iJtLj2fR3Z8AHOJ+kvK9D5TzvC38qvlrPkwbwHjP9mx9mgNODDd3BiEC3w08YJm/u6nkCkdrtdCUTkcHarI1KDXcKT2QOn0Hk0K7tpmbp81jpdQSQ2N3yqqmr+XY7sIj9smKQf101UrU5H7CQK6HY0cdj5QlbJ1suZ5tKpWGCep56yZQT/n6R3AMBT3bIKARIfkzPlCkoSLeOFnkkuOtlKyjLjnQ3Mw+LzxesE=
  - secure: ymV0dDYc4x0qHz8j8ianv7Aw8so6/NaqAaGU9hcnex7QuYwW9xz2YjZ6loRjRaN1jsyPwYNhCj9p6o5v+4k0hRxQWD5InOBwIOQBNcfXPvz/1W7FnztyIXw5Ez7erR1CO+REtxjQCc34to8sobPBl24fiUD5LiCMKAnzp31EAR0wfXkeBA8Des606NPxU7f/QQYWQlTEAI7ZtlNtamTwUcOXz3gUYkM9oMRIsRcqul6q+lbXYpwFSkZsezEKxVw0X4ZrggK9v9YEhvvqOJoMAyz2KGyNVLwE4xsBMVRBqEzT5WYCBNOm2QjEfmj39zk46yz7Z/EUdYcDWQQwZ7p1gZ/YMu6f5t9ggb/LLuNszcIzEz12iUp283xKvPP6IGNFduo9mQPiMV10L/a3PpNwAeQsb0sWLj+58z6lwl7dXKhcl/qW+VUTRqKLyIQPAuSsRHvR0qcNcFx9K3rbac8dr7xwBWZXiAW4gTCOc6NoOMrnTzDwWPjpFDH4i5d/39E+fPI11FssJYMPvLa2vh7qGbj7ntBw+NTtBxAG3vui4Tda9cjjquUZQopCzw4PCQM/eRKCM5Gva0trrqNmpHbeDWXh6OzSQLHtvA+IeEywDqY240Go4VDY/dWHSregpvAVrSRD5JZNsxb1TX1SgDdAfYKVoJOxq4fVTIQtclSD0T0=
notifications:
  slack:
    secure: xYTqHowKT9fkEz3hnd8q3uJGIW+clEUwOxc46tg/s0k5/0KzRS1BdvbLM6AWN4zpTII9AHiYU8mE39vICNXUrrLs7xhRm/gXOiACplGvdbvMliUY9jBDRW2N8muexz1sqTqy5qFp/vmJKHqeQKGSkamyE4Bv8Tg/0MnJMx6piNj8NqLWWiuosJbvt4kY6ZInB33NTrt7AQuaqnHPrL0eADQNxORNHDbnOsmVl7ApswEnUndEZ+h6abXgZAIelFhJTuOYnH2Py+XpcdxPNK7udy/qL78Aji1WrDxKMnY+Lhq1jhQGez0hMlpZyoaLVNkh5ZhWIgJB3zI3rg9ndNKEqGL0MreRsm2h1yFQMPMzItJ3xcsi8OWi62P8cA1AKFpzEZAZuZN+bOKStWdDUwOOeQXbYb137Fs7l8da2Wx+JuQc0FsxFqYSV5fV0aXjviNa16eB8xsUOKCx7fU3O9CTkxdqn+Evn1RMSCvSVlJwv3v+SESg+17TCFxk+m7AqJxPiewqzqODqY2WHOiQAGHT2x7vVp2QH0gqOBWYjXT+UyFFS6Mq7fzXx49wbBrOBzCnnURSWJ1k1/HGNyU19pFI95PDinhLrwVQ9ZzZ5ewm5W41vI/tHKZyIim9v4lpYByznMu0AlJ6PuWaNL5I1tnvbn9OPPDU8eWMpoDmelr7Tgk=
