apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: named
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: named
