apiVersion: apps/v1
kind: Deployment
metadata:
  name: named
  labels: 
    app: named 
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: named
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: named
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        nais.io/logformat: glog
    spec:
      containers:
      - name: named
        image: "{{ .Values.repository }}:{{ .Values.version }}"
        resources:
          requests:
            memory: "{{ .Values.request.memory }}"
            cpu: "{{ .Values.request.cpu }}"
          limits:
            memory: "{{ .Values.limit.memory }}"
            cpu: "{{ .Values.limit.cpu }}"
        livenessProbe:
          httpGet:
            path: /isalive
            port: http
        env:
          - name: fasit_url
            value: "{{ .Values.fasitUrl }}"
          - name: cluster_name
            value: "{{ .Values.clusterName }}"
        ports:
        - containerPort: 8081
          protocol: TCP
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["all"]
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: {{ .Values.runAsUser }}
