apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: named
spec:
  rules:
  - host: "{{ .Values.ingress }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: named
          servicePort: 80
