apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: named
spec:
  rules:
  - host: "{{ .Values.ingress }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: named
            port:
              number: 80
